### ISSUE TITLE
Визначити тривалість днів відведених для походу

### ISSUE THREAD

**Issue by annachopyk** [annachopyk/ITinEducation#1]

**Comment by annachopyk** [comment]
Всім привіт. Ідеальний час, щоб обговорити похід в гори (Хвилинка сарказму).
Для початку давайте визначимо, хто на скільки днів може вибратися в гори і коли.

**Comment by Martaa19** [comment]
Добрий ранок, ну або не дуже.
Я маю хороший маршрут, але він триває біля чотирьох днів. Тому давайте заплануємо похід на чотири дні, якшо ви не проти

**Comment by annachopyk** [comment]
Я не витримаю 4 дні, максимум 3

**Comment by annachopyk** [comment]
Такс, якщо ми хочемо обрати 3 дні, тоді я можу з 14 по 16 жовтня.

**Comment by Martaa19** [comment]
оо, 14 свято думаю я теж зможу у ці вихідні

**Comment by Martaa19** [comment]
потрібно ще тільки спитати Яну

**Comment by Martaa19** [comment]
я зараз покажу вам маршрут який мені подобається і тоді вже вирішимо

**Comment by annachopyk** [comment]
для обговорення марштуру є окреме ішю)

**Comment by Martaa19** [comment]
так, я вкурсі)

**Comment by annachopyk** [comment]
Такс, я передумала, я зможу на 4 дні

**Comment by Yana3456** [comment]
я думаю теж зможу на 4 дні, але якщо це буде п'ятниця-понеділок

**Comment by Martaa19** [comment]
це якраз так і буде, 14-17 жовтня

**Comment by Yana3456** [comment]
о супер, тоді визначились

**Comment by Martaa19** [comment]
супер, закриваю це ішю!

**Comment by Yana3456** [comment]
в мене якраз празник 14, я вам солодкого візьму в дорогу))
