### ISSUE TITLE
Написати список особистих речей які потрібні у поході

### ISSUE THREAD

**Issue by Martaa19** [annachopyk/ITinEducation#10]

**Comment by Martaa19** [comment]
це обговорення слугуватиме більше як нотатник для вас, тому тут напишіть речі які будете класти у свій рюкзак

**Comment by Martaa19** [comment]
мій список:
3-4 пари теплих шкарпеток
непромокаюче взуття
і якісь кроси на зміну
зубна щітка і паста
щітка для волосся
2 теплих светри
футболка
термобілизна
зручні штани
і непромокаюча куртка
шапка або кепка
дощовик

**Comment by Martaa19** [comment]
і ще посуд і прибори з якого будемо їсти

**Comment by Yana3456** [comment]
ну у мене принципі все теж саме, там ще можна взяти пачку мокрих салфеток, павербанк обов'язково

**Comment by Martaa19** [comment]
о так, за зарядку я забула, ще можна колонку взяти, щоб веселіше було йти

**Comment by annachopyk** [comment]
можна взяти паперові карти для орієнтування по місцевості

**Comment by Martaa19** [comment]
Ахахаха, Аня, я в карті Львова розібратись не можу паперовій, а ти мені хочеш гірну дати

**Comment by annachopyk** [comment]
насправді твій список універсальний, хороший перелік, тому думаю, що тут ми визначилися

**Comment by annachopyk** [comment]
лайкніть, якщо все гуд)

**Comment by Martaa19** [comment]
Все добре)
