### ISSUE TITLE
І скласти відповідне меню, що ми будемо їсти в горах

### ISSUE THREAD

**Issue by Martaa19** [annachopyk/ITinEducation#11]

**Comment by Yana3456** [comment]
я зайця з гуртожитку візьму

**Comment by Martaa19** [comment]
ми будемо готувати твого зайця?

**Comment by Martaa19** [comment]
на сніданки пропоную запарити вівсянку з сухофруктами, досить ситно і корисно
на перекуси можна енергетичні і шоколадні батончики

**Comment by Martaa19** [comment]
тепер потрібно щось на обід і на вечерю що швидко готується

**Comment by Yana3456** [comment]
мені вівсянки на довго не хватає(і на воді вона бєєє

**Comment by Martaa19** [comment]
що пропонуєш тоді на сніданок?

**Comment by Yana3456** [comment]
тому на сніданок пропоную каву-чай печиво і можна звичайні канапки зробити, якраз до ранку ще нічого не зіпсується(є ці нарізки вже готові)

**Comment by Yana3456** [comment]
перекуси так і будуть батончики, горішки

**Comment by Yana3456** [comment]
чорт, в мене тут нагетси горять, вернусь через декілька хвилин

**Comment by Martaa19** [comment]
@annachopyk тобі на сніданок підходить вівсянка чи теж не любиш?

**Comment by annachopyk** [comment]
15 років підряд їм її на сніданок, тому ідеально

**Comment by annachopyk** [comment]
від нагетсів теж не відмовилась б))

**Comment by Martaa19** [comment]
отже тоді в нас з Аньою на сніданок вівсянка, в Яни канапки

**Comment by Martaa19** [comment]
на обід потрібно щось таке що швидко готується,  можна мівіну або інші страви які запарюються

**Comment by Yana3456** [comment]
добре, тільки потім що не заздрили сильно))

**Comment by Martaa19** [comment]
та в нас теж капапки будуть тільки + вівсянка ще

**Comment by Yana3456** [comment]
@Martaa19 мівінка підходить, або є такі супчики швидкого приготування

**Comment by Martaa19** [comment]
що ще?

**Comment by Yana3456** [comment]
вони в пакетиках продаються

**Comment by Yana3456** [comment]
в сільпо є, залити кип'ятком і готово

**Comment by Yana3456** [comment]
далі... вечеря?

**Comment by Martaa19** [comment]
так

**Comment by Martaa19** [comment]
на вечір можна гречку зварити, в нас буде пальник то можна буде зварити

**Comment by Martaa19** [comment]
і до гречки можна сосиски

**Comment by Yana3456** [comment]
вони нам не зіпсуються? хіба ці сирокопчені

**Comment by Martaa19** [comment]
та та, кабаноси я мала на увазі

**Comment by Yana3456** [comment]
окей, Аня підходить? в інші дні можна комбінувати, там макарони з консервами чи каша(кус кус)

**Comment by Martaa19** [comment]
то ще макарони і кашу беремо?

**Comment by Martaa19** [comment]
гречка швидше запарюється ніж варяться макарони, тому пропоную її

**Comment by annachopyk** [comment]
я не люблю їсти, тому з мене досить вівсянки, + батончики + сухофрукти + горішки

**Comment by Martaa19** [comment]
Є вже в мене такий один знайомий який не любить їсти, тому давай не заганяй себе ще ти в депресію і з нами будеш їсти добре!

**Comment by annachopyk** [comment]
ахаа, добре, не маю часу на депресію. І гречку візьмемо.

**Comment by annachopyk** [comment]
тут все вирішено, так?

**Comment by Martaa19** [comment]
супер, все вирішили
