### ISSUE TITLE
Знайти відповідний гірський маршрут

### ISSUE THREAD

**Issue by annachopyk** [annachopyk/ITinEducation#2]

**Comment by Martaa19** [comment]
Дівчата, я про цей похід цим маршрутом мрію вже два роки
ось посилання на опис маршруту, чекаю ваш фідбек
https://vpohid.com.ua/routes/v/route/12/

**Comment by annachopyk** [comment]
О, Озеро Бребенескул, я так багато чула про нього, хочу-хлчу-хочу

**Comment by annachopyk** [comment]
Але тут тривалість 4 дні, ми можемо його скоротити?

**Comment by Martaa19** [comment]
думаю можемо не піти на одну з вершин і тоді скоротимо на один день

**Comment by Martaa19** [comment]
![image](https://user-images.githubusercontent.com/90724231/194938956-1613700a-cd8a-4299-8e67-1ed988e25a39.png)
ось яке воно прекрасне

**Comment by annachopyk** [comment]
Йоооййй, такаккккк, аж реально захотіла цю поїздку.

**Comment by Martaa19** [comment]
ми точно мусимо піти колись в цей похід!

**Comment by annachopyk** [comment]
"Зверніть увагу. Цей маршрут проходить через межу "Карпатького біосферного заповідника". На КПП між Петросом та Говерлою (на "перемичці") потрібно оплатити за вхід в заповідник. 30 грн з особи за добу перебування в заповіднику."

Треба почитати про це

**Comment by Martaa19** [comment]
я позичу тобі 30 гривень

**Comment by annachopyk** [comment]
Та вже могла сказати, що оплатиш мені вхід

**Comment by Martaa19** [comment]
аахахх, ну добре, це буде мій подарунок тобі на дн

**Comment by annachopyk** [comment]
Вирішено йдемо! Чекаємо одобрення Яни.

**Comment by Yana3456** [comment]
Я сильно перепрошую, бо з тими тривогами ніяк не змогла підключитись до розмови

**Comment by Yana3456** [comment]
мені все подобається, краєвили бомбезні просто

**Comment by Martaa19** [comment]
оскільки ми визначились що похід триватиме 4 дні, то маршрут вздовж чорногірського хребта нам підходить повністю

**Comment by Martaa19** [comment]
@annachopyk ти дізналась про оце "Зверніть увагу. Цей маршрут проходить через межу "Карпатького біосферного заповідника". На КПП між Петросом та Говерлою (на "перемичці") потрібно оплатити за вхід в заповідник. 30 грн з особи за добу перебування в заповіднику."?

**Comment by Yana3456** [comment]
повністю))

**Comment by annachopyk** [comment]
@Martaa19 не дізналася, але можемо зайти, нам ж по дорозі

**Comment by Martaa19** [comment]
добре, хоч раз в житті побуваю в заповіднику

**Comment by Martaa19** [comment]
наче з маршрутом все визначили, думаю можна це обговорення закривати
