### ISSUE TITLE
Знайти спосіб добирання до початкового місця

### ISSUE THREAD

**Issue by annachopyk** [annachopyk/ITinEducation#3]

**Comment by Martaa19** [comment]
що я пропоную на рахунок добирання: можна потягом зі Львову прямо у Кваси, або блаблакаром але це вийде дорожче, я голосую за бюджетний варіант

**Comment by Martaa19** [comment]
скажіть що вам більше до вподоби і я тоді буду шукати квитки, щоб забронювати нам місця

**Comment by annachopyk** [comment]
Я теж голосую за бюджетний варіант. Написати Сергію, хай нас всіх завезе, ахаха (Хвилинка жарту)

**Comment by annachopyk** [comment]
А якщо серйозно, треба пошукати електрички, або я маю групу в телеграмі, де люди шукають собі компанію в дорогу, вийде дешевше, ніж блаблакар

**Comment by Martaa19** [comment]
ой Аню, думаю краще не варто Сергія турбувати

**Comment by Martaa19** [comment]
зараз я скину варіанти поїздів 14 жовтня

**Comment by annachopyk** [comment]
Ахаха, не хочеш такого компанйона в гори. Але ми на Високий замок з важкістю дійшли,про гори мовчу вже. Окей, не відволікаємося. Я йду моніторити групу в телеграмі, а ти глянь на розклад електричок. Нам треба ранішню годину.

**Comment by Martaa19** [comment]
дивіться є такі два варіанти, якщо ми виїдемо вночі то приїдемо десь перед обідом, думаю опимально 
![image](https://user-images.githubusercontent.com/90724231/194938073-424db2f3-c8c2-4b4e-9716-db26d43cdf3d.png)

**Comment by annachopyk** [comment]
А ми зможемо о комендантській годині заїхати на вокзал? Бо минулого разу як я добиралася з гір додому, о 23 год, це було нереально важко викликати таксі. А тут ранок і коменданська година...

**Comment by annachopyk** [comment]
Можливо нам треба добратися до того села, переночувати там десь, і на наступний день йти в гори?

**Comment by Martaa19** [comment]
ну тоді на похід вже точно треба виділити 4 дні

**Comment by annachopyk** [comment]
ну, тоді хай буде, візьму вихідний. Буду відновлювати емоційний стан

**Comment by Martaa19** [comment]
я тут дослідила і інших потягів немає, тому мусимо обирати з наявного

**Comment by annachopyk** [comment]
Давай Київ - Рахів

**Comment by Martaa19** [comment]
думаю якщо домовитись з таксі завчасно, то можливо тоді не буде проблем

**Comment by Martaa19** [comment]
добре, я бронюю нам трьом квитки

**Comment by annachopyk** [comment]
Супер. Закриваю це питання.
