### ISSUE TITLE
Знайти місце оренди спорядження

### ISSUE THREAD

**Issue by annachopyk** [annachopyk/ITinEducation#4]

**Comment by Martaa19** [comment]
На рахунок спорядження нам потрібно: спальник, каремат для кожного і також одна трьохмісна палатка, і також трекингові палиці і пальник

**Comment by Martaa19** [comment]
спальник і каремат та палатку я маю вдома тому візьму, зараз скину хороші магазини прокату у Львові і ви щось оберете собі

**Comment by Martaa19** [comment]
ось цей хороший магазин тільки трішки дорого https://www.gorgany.com/?gclid=Cj0KCQjwhY-aBhCUARIsALNIC078lzkC9Y4bo7swoyb6c5RSW5ztuGB2T5pPdS3DkurgVFM_W8H01EAaAu-NEALw_wcB
https://www.robinzon-ua.com.ua/ukr/ ще такий магазин є
потрібно обирати

**Comment by annachopyk** [comment]
Такс, я маю рюкзак, і спеціальний посуд

**Comment by Martaa19** [comment]
мені потрібно лише трекингові палиці, зараз оберу собі

**Comment by annachopyk** [comment]
я не маю дощовика, точніше той,що я маю не підійде

**Comment by annachopyk** [comment]
давайте кожен складе список, і хтось 1 все забронює

**Comment by Martaa19** [comment]
згода

**Comment by annachopyk** [comment]
а, стоп, це магазин, а не оренда, так?

**Comment by Martaa19** [comment]
там є оренда теж, ти який дивишся?

**Comment by Martaa19** [comment]
дивіться, це магазин моїх знайомих, тут наче оптимальні ціни 
![photo1665431602](https://user-images.githubusercontent.com/90724231/194942584-6c3eef57-5099-4baa-9725-0ba837d375c8.jpeg)

**Comment by Yana3456** [comment]
я маю палатку, нещодавно попала на акцію і купила. Вона дуже крута

**Comment by Yana3456** [comment]
Спальник для себе теж маю, щодо карематів то пройдусь по гуртожитку, думаю не відмовлять

**Comment by Yana3456** [comment]
В нас просто під час тривоги усі беруть каремати у підвал. Може не зажаднічають

**Comment by annachopyk** [comment]
@Yana3456  Може ти мені дощовик ще знайдеш?

**Comment by Martaa19** [comment]
але чи потрібно нам дві палатки ?)
вона в тебе одномісна ?

**Comment by Yana3456** [comment]
двохмісна

**Comment by Martaa19** [comment]
в мене теж наче двомісна, хтось один тоді буде ночувати сам

**Comment by annachopyk** [comment]
Я боюся одна)

**Comment by Yana3456** [comment]
я теж

**Comment by annachopyk** [comment]
Я тут від стресу схудла на 1 кг, тому точно поміщуся біля вас

**Comment by Yana3456** [comment]
а ми троє не помістимось?

**Comment by Martaa19** [comment]
троє з рюкзаками і всіма речима в двомісній палатці? думаю що ні(

**Comment by Yana3456** [comment]
то можемо в одну палатку речі покласти, а в іншій спати))

**Comment by Martaa19** [comment]
оо, хороша ідея!

**Comment by annachopyk** [comment]
наш гід буде шокований, брати палатку, як кладовку

**Comment by Martaa19** [comment]
ахахаххаахаххахаах

**Comment by Yana3456** [comment]
ахахах не бачу іншого виходу

**Comment by Yana3456** [comment]
> 

а що з твоїм? ти ж мала

**Comment by Martaa19** [comment]
що мала і ти до кого?

**Comment by Yana3456** [comment]
дощовик, до Ані, забула тегнути

**Comment by Martaa19** [comment]
добре, @Yana3456 тобі по спорядженню що потрібно, щось береш напрокат? і @annachopyk також?

**Comment by Yana3456** [comment]
у мене все є, тому я нічого))

**Comment by Martaa19** [comment]
мені потрібні лише трекингові палиці і ще нам потрібен пальник, нікого вдома немає?

**Comment by Yana3456** [comment]
в мене лише один

**Comment by Martaa19** [comment]
а нам  в горах потрібно два?

**Comment by Yana3456** [comment]
прочитала спальник...лол
Пальника немаю, треба брати в оренду напевно

**Comment by Martaa19** [comment]
тоді треба пальник, мені палиці, і ще чекаємо що Ані потрібно і тоді буду бронювати

**Comment by annachopyk** [comment]
Мені палиці, спальник маю, каремат теж маю.
