### ISSUE TITLE
Знайти гіда

### ISSUE THREAD

**Issue by annachopyk** [annachopyk/ITinEducation#5]

**Comment by Martaa19** [comment]
на рахунок гіда, памятаєте я розповідала що в мене є знайомий який живе в горах, думаю за сувеніри зі Львова він погодиться піти з нами в похід, чи у вас є інші пропозиції?

**Comment by annachopyk** [comment]
повністю підтримую, але треба йому описати рівень нашої підготовки, але описати так, щоб не злякати його

**Comment by Martaa19** [comment]
напишу приблизно так: "привіт, ходи  з нами в похід, але  в нас нульова підготовка"

**Comment by annachopyk** [comment]
коли ти можеш з ним зв'язатися?

**Comment by Martaa19** [comment]
напишу йому завтра зранку

**Comment by annachopyk** [comment]
Окей, і на всяк випадок треба звантажити офлайн карти

**Comment by Martaa19** [comment]
привіт, писала я своєму знайомому, він сказав що впринципі не проти походу, але зараз трішки холодно, тому сказав брати теплі речі з  собою(п.с уявимо, що ми йдемо влітку в похід)

**Comment by Yana3456** [comment]
Мені Іра скинула одного чувачка в інсті, він доволі часто ходить у походи. Зараз попробую його знайти

**Comment by Martaa19** [comment]
давай пробуй, і дізнайся зразу про ціну

**Comment by Yana3456** [comment]
не можу знайти, якщо попадеться то скину

**Comment by Martaa19** [comment]
ну тоді я домовляюсь на ці вихідні з своїм знайомим та й все, нема чого затягувати, в вас через 3 дні похід вже!

**Comment by annachopyk** [comment]
так, тоді @Martaa19 ти пиши до нього. Ти впевнена, що він погодиться?

**Comment by Martaa19** [comment]
ну він наче погодився вже, головне йому не казати що ми жодного разу в похід не ходили, ахахах
