### ISSUE TITLE
Купити їжу

### ISSUE THREAD

**Issue by annachopyk** [annachopyk/ITinEducation#6]

**Comment by Martaa19** [comment]
привіт, давайте почнемо обговорення на рахунок їжі, це дуже важливий пункт

**Comment by Martaa19** [comment]
я знаю, що продаються спеціальні набори для походів, або ж купимо просто їжу і у ще одному обговоренні обговоримо меню

**Comment by annachopyk** [comment]
думаю, що легше купити набір, але це вийде дорожче, в нас пріорітет ціна чи легкість?

**Comment by Martaa19** [comment]
ну так як ми студенти яким ще й невчасно виплачують стипендію то думаю що ціна важлива складова

**Comment by annachopyk** [comment]
може ми самі ці набори складемо, що скажеш?

**Comment by Martaa19** [comment]
там вже приготовлена сублімована або сушена їжа, в нас немає дивайсів таких щоб зробити щось схоже

**Comment by Yana3456** [comment]
а деяким стипендія і не виплачується, тому я за ціну

**Comment by Yana3456** [comment]
нам потрібна для початку вода(хоча б 2 літри, пусті пляшки), горішки, батончики, консерви, крупи, сіль, перець, кава-чай, печиво сухе, макарони і думаю достатньо

**Comment by Martaa19** [comment]
давайте в іншому ішю напишемо що ми будемо готувати, а тоді вже тут напишемо продукти які  нам треба

**Comment by Yana3456** [comment]
так я написала які продукти треба, це не складене меню))

**Comment by Yana3456** [comment]
а сорі, не так зрозуміла... спочатку меню, а потім сюди продукти

**Comment by Martaa19** [comment]
список їжі:
шоколадні батончики 
енергетичні батончики
мівіна
супи які запарюються
вівсянка
сухофрукти
горішки
хліб
ковбаса
сир

**Comment by Martaa19** [comment]
що я пропустила?

**Comment by annachopyk** [comment]
Там є джерела по дорозі?

**Comment by annachopyk** [comment]
Думаю на рахунок води

**Comment by Martaa19** [comment]
так, джерела звичайно є, але на перший день треба взяти воду з собою

**Comment by Martaa19** [comment]
отже продублюю
список їжі:
шоколадні батончики
енергетичні батончики
мівіна
супи які запарюються
вівсянка
сухофрукти
горішки
хліб
ковбаса
сир
гречка або кус-кус
кабаноси
цукерки
вода

**Comment by Martaa19** [comment]
ну наче по їжі все)
