### ISSUE TITLE
Скласти аптечку

### ISSUE THREAD

**Issue by annachopyk** [annachopyk/ITinEducation#7]

**Comment by Martaa19** [comment]
це найголовніше обговорення яке можна було тільки придумати, бо з вами в похід йде бабулька Марта яку часто болить серце, ниє спина, болять ноги та голова на погоду, тому медикаментів треба брати більше ніж їжі

**Comment by annachopyk** [comment]
Тоді я беру для серця і нашатирний спирт

**Comment by Martaa19** [comment]
а інші 50 видів таблеток я беру?

**Comment by annachopyk** [comment]
Мені головне від алергії щось взяти, і з мене достатньо.

**Comment by Martaa19** [comment]
я тут знайшла сайт де вже є зібрана аптечка, тому можемо подивитись і виписати лише то що нам потрібно
https://www.gorgany.com/pro/first-aid-kit/

**Comment by Yana3456** [comment]
о мені треба шось від голови і горла

**Comment by Yana3456** [comment]
мені хватить ковтка гірської води і в мене запалення горла)

**Comment by Martaa19** [comment]
@Yana3456 тобі треба щоб в струмках текла не джерельна вода, а кипячений чай

**Comment by Yana3456** [comment]
ахаххаха бажано

**Comment by Yana3456** [comment]
і то вже нехай буде зелений

**Comment by Yana3456** [comment]
![2022-10-11 13 43 49](https://user-images.githubusercontent.com/76550705/195070221-b17a3e0f-2a59-47f3-ada2-2610acf6ceb8.jpg)

**Comment by Yana3456** [comment]
ой яка велика картинка вийшла((

**Comment by annachopyk** [comment]
Ви забули від алергії для мене щось !!!!!!

**Comment by annachopyk** [comment]
Бо буду всю дорогу плакати (сльози від алергії)

**Comment by Yana3456** [comment]
я написала, просто не знаю назв

**Comment by Yana3456** [comment]
там ж написано.... від алергії щось))

**Comment by Martaa19** [comment]
тепер давайте поділимо хто що купує

**Comment by Martaa19** [comment]
в мене вдома є серцеві і  заспокійливі візьму їх

**Comment by Martaa19** [comment]
таблетки від температури і знеболюючі я куплю, все інше беріть ви

**Comment by annachopyk** [comment]
Тоді решта таблеток на мені. Без проблем. Все вирішено?

**Comment by Martaa19** [comment]
може Яна хоче якісь таблетки ще взяти

**Comment by annachopyk** [comment]
@Yana3456 візьми пластир і антисептик

**Comment by Yana3456** [comment]
без проблем
