### ISSUE TITLE
Знайти чим добратись додому з кінцевої точки маршруту

### ISSUE THREAD

**Issue by Martaa19** [annachopyk/ITinEducation#9]

**Comment by Martaa19** [comment]
кінцева точка маршруту - Дземброня, отже є такі варіанти що з Дземброні трансфером до Ворохти, а з ворохти потягом

**Comment by Martaa19** [comment]
є два варіанти 
![image](https://user-images.githubusercontent.com/90724231/195103015-99923368-6893-4ee2-9908-b88433d915b5.png)

**Comment by Martaa19** [comment]
за який голосуєте?

**Comment by annachopyk** [comment]
я голосую за 2, невідомо, коли ми точно доберемося до кінцевої точки

**Comment by Martaa19** [comment]
Окей, тоді бронюю квитки на 19:45
